### ISSUE TITLE
下载合集时，如果合集中内容过多，会导致内存占用过高最终程序崩溃

### ISSUE THREAD

**Issue by youmaqian** [ktxiaok/L4D2AddonAssistant#7]
# 下载内容过多的合集时内存会占用过高导致程序崩溃
#### 比如在下载合集[《必玩三方图 》](https://steamcommunity.com/sharedfiles/filedetails/?id=3292405380) 时，程序内存占用一直在上升
![48ff1a421d546708edc267a9a51792b](https://github.com/user-attachments/assets/f3c8d66a-8d70-47b9-9fdd-62e641c8a1ed)

### （如果没崩，下载完后内存会慢慢下降，但最终还是会占用1000多MB内存）
![d4f38e58b1dc7a1ec9dd97df076e6d4](https://github.com/user-attachments/assets/06602211-eba3-4411-9cba-00e1b5bc3297)
###########################################分割线#############################################
![a069abe2b9df3de67f7cce7ad1d02e7](https://github.com/user-attachments/assets/12d0254a-a0e7-4687-863d-370c8cb38e5a)

### 比如我在下载[【制作瞄准功能的武器MOD合集】](https://steamcommunity.com/sharedfiles/filedetails/?id=3334564847)时便没有多少内存占用就下完了，如图下
![image](https://github.com/user-attachments/assets/106a4081-af9a-4748-a9b3-eb301d3339c5)
## 在下载合集时，无论合集中内容有多少任务都会同时下载（可能是问题的元凶），可以考虑设置一个一次最多同时下载数量上限，比如一次最多同时进行三个下载任务,下载完一个任务再开启下一个任务，让其他的任务处于等待中
![3f3489f9e4fe1b86ba14367c17bf038](https://github.com/user-attachments/assets/26a428b7-51e8-4245-8d83-4e26b22d6153)
### 使用建议，多选时虽然可以按住Ctrl然后多选，但一个一个手动去点的话效率太慢了
![a1eebe819dde8825057fa5f8471643e](https://github.com/user-attachments/assets/eb9b44a9-69e6-4793-abfd-8382ac0b38d8)
#### 可以设置一个按住鼠标多选，如图所示
![ba707663595a51412f99a6c37e6c777](https://github.com/user-attachments/assets/11b02033-8d16-4a25-9edd-d71c80c3b1a8)
#### 还可以像MC一样，同时摁住Ctrl和鼠标左键然后拖动鼠标，就可以把经过的Mod全选上
![image](https://github.com/user-attachments/assets/22f3a99c-66d6-4b78-89d2-b7787918484f)

**Comment by youmaqian** [comment]
如果崩溃后重新打开继续下载，还是可以完成任务的

**Comment by youmaqian** [comment]
我感觉跟一次性同时下载太多任务有关，我一个一个下就没有任何问题

**Comment by ktxiaok** [comment]
非常感谢你的反馈~我会在下个版本修复此下载问题。关于多选的问题，现在是可以用Shift进行连选的。

**Comment by youmaqian** [comment]
> 非常感谢你的反馈~我会在下个版本修复此下载问题。关于多选的问题，现在是可以用Shift进行连选的。

抱歉，我没有注意到，谢谢指点

**Comment by ktxiaok** [comment]
> > 非常感谢你的反馈~我会在下个版本修复此下载问题。关于多选的问题，现在是可以用Shift进行连选的。
> 
> 抱歉，我没有注意到，谢谢指点

没事~

**Comment by ktxiaok** [comment]
问题已在版本0.5.1中修复。
